version: "3.3"

services:
  login-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 9090:9090
    environment:
      - LOGIN_HTTP_PORT=80
      - LOGIN_GRPC_PORT=9090
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=canary
      - MYSQL_USER=canary
      - MYSQL_PASS=canary
      - SERVER_NAME=Canary
      - SERVER_IP=127.0.0.1
      - SERVER_PORT=7172
      - SERVER_LOCATION=NL
      - RATE_LIMITER_RATE=3000000000000
      - RATE_LIMITER_BURST=53000000000000
