---
name: Analysis - Golang Lint

on:
  workflow_call:

jobs:
  job:
    name: Golang Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.x"

      - name: Golang Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
