---
name: Analysis - Golang Lint

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  job:
    name: Golang Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Golang Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
