---
name: Analysis - SonarCloud

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: false

permissions:
  contents: read
  pull-requests: read

jobs:
  job:
    name: SonarCloud
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: SonarCloud Scan
        if: ${{ env.SONAR_TOKEN != '' }}
        continue-on-error: true
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
