---
name: Build - MacOS

on:
  workflow_call:

jobs:
  job:
    name: macos-15
    runs-on: macos-15
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.x"

      - name: Build Login Server
        run: go build -o login-server ./src/
