---
name: Build - Ubuntu

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        go-version: [1.16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Login Server
        run: go build -o login-server ./src/
