---
name: Build - Windows

on:
  workflow_call:

jobs:
  job:
    name: windows-2022
    runs-on: windows-2022
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Build Login Server
        run: go build -o login-server ./src/
