name: build
on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [main]
jobs:
  ubuntu-build:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: go build -o login-server ./src/