name: Cross-platform Build
on:
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: go build -o login-server ./src/