name: Cross-platform Build
on:
  pull_request:
    branches: [ '**' ]

jobs:
  full_ci:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
    runs-on: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: go build ./src/