name: Go Test Coverage

on:
  pull_request:
    branches: [ '**' ]

jobs:
  coverage:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate coverage report
        run: |
          go test ./tests `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella